Project setup
Ouail-01/Math-Magicians_Calculator pull request #1
Opened 2023-02-13 21:06 UTC by Ouail-01

> ### In this pull request, I'm gonna set up the environment and tools needed to develop a React application.

# Learning objectives :
- Set up a React app.
- Use React documentation.

2023-02-13 21:28 UTC, brainconnect93 reviewed
Hi @Ouail-01,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

<img src="https://camo.githubusercontent.com/999c41ff216bced575a5c7873c1c4ed04ef945c867ca87788003794670ee5aa7/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f785550476377453343556b586c766f6e75672f67697068792e676966">

## Invalid Code Review Request

- [ ] Kindly setup linters environment for this milestone using the appropriate linters file template given to us by microverse

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

_Cheers and Happy coding!👏👏👏_

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

-----

_Invalid Code Review Request does not count into the code reviews limit._

2023-02-14 03:30 UTC, t-yanick requested changes
Hi @Ouail-01 , 

### Good job so far!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  App created with Create React App
:heavy_check_mark: All linters passing and Pull Request is Descriptive

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-14 03:30 UTC, t-yanick commented on README.md
> +> [Comming soon !!]()
- [ ] Great job working on this milestone. I understanding you don't yet have a live demo link, but you should not make your coming soon a link which gives an error 404. We have to avoid having broken links in our codebase.
![Screen Shot 2023-02-13 at 7 23 21 PM](https://user-images.githubusercontent.com/62849872/218631330-8e0732b5-6649-4331-b22f-1970f3a1274c.png)

2023-02-14 03:51 UTC, Davidosky007 approved these changes
Hi @Ouail-01 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
* No linter errors 👍 
* Well written PR description 👍 
* Good looking readme file 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-14 04:16 UTC, merged